### ISSUE TITLE
How to recognize the fl2000 on system.

### ISSUE THREAD

**Issue by dv-vb** [fresco-fl2000/fl2000#2]
It seems like the driver can be used on my linux, and the sample on github work well: the new screen can output color out, but the display setting of system can't recognize the new screen which connect with usb2vga device which use fl2000. Is there anything lost for me?
Btw, there happened some error which fltest just stop after create_surface when I copy ko to /lib/modules/`uname -r`/  and modprobe fl2000, I do this hope the driver can be insmod auto when system startup.

**Comment by fresco-fl2000** [comment]
Hi,
you do not miss anything. Currently the driver does NOT interact with the X system, and therefore the screen isn't recognized. As described in the README, the driver merely implements the USB display logic, it couldn't do desktop manipulation (mirrored vs extended desktop).
