### ISSUE TITLE
FL2000-2.1.33676.0

### ISSUE THREAD

**Issue by damnhalfling** [fresco-fl2000/fl2000#4]
Hello;

I would like to know if this driver work for usb3.0 to HDMI FL2000-2.1.33676.0 ???? 

I compiled this with some changes to my kernel, i use debian stretch!! when i try to use the sample i have "this fl2000 device not connected?"

Is there a driver for usb to hdmi????

Thanks

**Comment by fresco-fl2000** [comment]
hi ,
FL2000 HDMI support is under development. It should be ready within 1 month.
